version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    privileged: true
    restart: always
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlddl
      - TZ=Asia/Shanghai
    volumes:
      - "~/data/mysql_data:/var/lib/mysql"
    networks:
      - my-net

networks:
  my-net:
    external: true



